### ISSUE TITLE
uart port not being detected

### ISSUE THREAD

**Issue by 2vin2vin** [WeActTC/Nano_TX2-Xavier_NX-CB#10]
Hi,
I have been trying to use the uart1 and uart2 on the board for communicating with another device but the port doesn't seem to get detected. I have checked with all the 4 boards that I have and it doesn't seem to work. 

I would like to know the logic level voltage for uart communication on the board.

**Comment by Greetrix** [comment]
Hi 2vin2vin,
     The UART logic level is 3.3V.
