### ISSUE TITLE
unable to boot from sd card

### ISSUE THREAD

**Issue by 2vin2vin** [WeActTC/Nano_TX2-Xavier_NX-CB#11]
Hi,
I have purchased 10 boards and I have been following the docs to boot from sd card. 1 board doesn't seem to be detected at all to even do nvidia flash while the other three are failing at some or the other point in the process.

**Comment by Greetrix** [comment]
Hi,
    Sorry to late reply.
    Can you contact with the Shop seller and get our service email. It can get the fastest response.
     Thanks.
