### ISSUE TITLE
Flashing OS

### ISSUE THREAD

**Issue by sujaymhaske1** [WeActTC/Nano_TX2-Xavier_NX-CB#2]
I have flashed Jetpack OS on SD card and then inserted it in the carrier board, but I am seeing no output on the screen via HDMI cable.

What should I do ?

**Comment by Greetrix** [comment]
Hi, What core board are you use, and the OS on SD card should push in core board SD. No CarrierBoard SD. Please contact the store you purchased for help, Thanks.
